window.COURSE_CONFIG = {
    slug: "biology",
    title: "Biology Study Resources",
    subtitle: "Click a topic to see videos and readings. Scan QR codes with your phone!",
    icon: "🧬",
    sheetUrl: "https://docs.google.com/spreadsheets/d/e/2PACX-1vTlnCCm8pU2GqY7wem-2Q6LyjLBFzFGBAB_mrDV0zZYotofEtvNfb1iSORE7WnOi0k9Gqlb8htIeC3m/pub?output=csv",
    tabs: [
        { id: "all", label: "All Topics" },
        { id: "Q1", label: "Q1: Foundations" },
        { id: "Q2", label: "Q2: Cells & Energy" },
        { id: "Q3", label: "Q3: DNA & Genetics" },
        { id: "Q4", label: "Q4: Evolution & Body Systems" }
    ],
    topics: [
        { code: "1A", name: "Observations vs. Inferences", tab: "Q1", group: 1 },
        { code: "1B", name: "Variables & Experimental Design", tab: "Q1", group: 1 },
        { code: "2A", name: "Characteristics of Life", tab: "Q1", group: 2 },
        { code: "2B", name: "Introduction to Homeostasis", tab: "Q1", group: 2 },
        { code: "3", name: "Ecosystems & Energy Flow", tab: "Q1", group: 3 },
        { code: "4", name: "The Carbon Cycle", tab: "Q1", group: 4 },
        { code: "5A", name: "Biodiversity & Ecological Succession", tab: "Q1", group: 5 },
        { code: "5B", name: "Human Impact on Ecosystems", tab: "Q1", group: 5 },
        { code: "6", name: "Population Dynamics", tab: "Q1", group: 6 },
        { code: "7A", name: "Atoms & Elements", tab: "Q1", group: 7 },
        { code: "7B", name: "Chemical Bonds", tab: "Q1", group: 7 },
        { code: "8A", name: "Polarity & Hydrogen Bonding", tab: "Q1", group: 8 },
        { code: "8B", name: "Cohesion & Adhesion", tab: "Q1", group: 8 },
        { code: "8C1", name: "High Specific Heat", tab: "Q1", group: 8 },
        { code: "8C2", name: "Evaporative Cooling", tab: "Q1", group: 8 },
        { code: "9A", name: "Carbohydrates & Lipids", tab: "Q1", group: 9 },
        { code: "9B1", name: "Protein Structure & Folding", tab: "Q1", group: 9 },
        { code: "9B2", name: "Nucleic Acids (DNA & RNA Intro)", tab: "Q1", group: 9 },
        { code: "10A", name: "Chemical Reactions Basics", tab: "Q1", group: 10 },
        { code: "10B", name: "How Enzymes Work", tab: "Q1", group: 10 },
        { code: "10C", name: "Factors Affecting Enzymes", tab: "Q1", group: 10 },
        { code: "11A1", name: "Endomembrane System", tab: "Q2", group: 11 },
        { code: "11A2", name: "Energy Organelles", tab: "Q2", group: 11 },
        { code: "11A3", name: "Plant vs. Animal Cells", tab: "Q2", group: 11 },
        { code: "11B", name: "Prokaryotes vs. Eukaryotes", tab: "Q2", group: 11 },
        { code: "12A", name: "Phospholipid Bilayer Structure", tab: "Q2", group: 12 },
        { code: "12B", name: "Membrane Proteins & Functions", tab: "Q2", group: 12 },
        { code: "13A1", name: "Simple Diffusion", tab: "Q2", group: 13 },
        { code: "13A2", name: "Facilitated Diffusion", tab: "Q2", group: 13 },
        { code: "13B1", name: "Osmosis Mechanics", tab: "Q2", group: 13 },
        { code: "13B2", name: "Tonicity & Cell Outcomes", tab: "Q2", group: 13 },
        { code: "13C1", name: "Membrane Pumps", tab: "Q2", group: 13 },
        { code: "13C2", name: "Bulk Transport (Endo/Exocytosis)", tab: "Q2", group: 13 },
        { code: "14A", name: "Virus Structure & The Life Debate", tab: "Q2", group: 14 },
        { code: "14B", name: "Lytic vs. Lysogenic Cycles", tab: "Q2", group: 14 },
        { code: "15", name: "Bacteria: Structure & Resistance", tab: "Q2", group: 15 },
        { code: "16A", name: "Light-Dependent Reactions", tab: "Q2", group: 16 },
        { code: "16B", name: "Calvin Cycle (Light-Independent)", tab: "Q2", group: 16 },
        { code: "17A", name: "Glycolysis", tab: "Q2", group: 17 },
        { code: "17B", name: "Krebs Cycle & Electron Transport", tab: "Q2", group: 17 },
        { code: "17C", name: "Fermentation", tab: "Q2", group: 17 },
        { code: "18A", name: "Cell Cycle Phases", tab: "Q3", group: 18 },
        { code: "18B", name: "Cell Cycle Checkpoints & Cancer", tab: "Q3", group: 18 },
        { code: "19A", name: "Mitosis Phases (PMAT)", tab: "Q3", group: 19 },
        { code: "19B", name: "Cytokinesis", tab: "Q3", group: 19 },
        { code: "20A", name: "The Structure of DNA", tab: "Q3", group: 20 },
        { code: "20B", name: "DNA Replication", tab: "Q3", group: 20 },
        { code: "21A", name: "DNA vs. RNA Structure", tab: "Q3", group: 21 },
        { code: "21B", name: "Transcription (DNA → mRNA)", tab: "Q3", group: 21 },
        { code: "22A", name: "The Genetic Code", tab: "Q3", group: 22 },
        { code: "22B", name: "The Process of Translation", tab: "Q3", group: 22 },
        { code: "23A", name: "Meiosis I: Reduction Division", tab: "Q3", group: 23 },
        { code: "23B", name: "Meiosis II: Sister Chromatid Separation", tab: "Q3", group: 23 },
        { code: "24A", name: "Crossing Over", tab: "Q3", group: 24 },
        { code: "24B", name: "Independent Assortment", tab: "Q3", group: 24 },
        { code: "24C", name: "Random Fertilization", tab: "Q3", group: 24 },
        { code: "25A", name: "Law of Segregation", tab: "Q3", group: 25 },
        { code: "25B", name: "Law of Independent Assortment", tab: "Q3", group: 25 },
        { code: "26A", name: "Monohybrid Crosses", tab: "Q3", group: 26 },
        { code: "26B", name: "Dihybrid Crosses", tab: "Q3", group: 26 },
        { code: "27", name: "Punnett Squares", tab: "Q3", group: 27 },
        { code: "28", name: "Pedigrees", tab: "Q3", group: 28 },
        { code: "29A", name: "Incomplete Dominance & Codominance", tab: "Q3", group: 29 },
        { code: "29B", name: "Multiple Alleles & Polygenic Traits", tab: "Q3", group: 29 },
        { code: "30", name: "Sex-Linked Traits", tab: "Q3", group: 30 },
        { code: "31A1", name: "Substitution Mutations", tab: "Q3", group: 31 },
        { code: "31A2", name: "Frameshift Mutations", tab: "Q3", group: 31 },
        { code: "31B", name: "Chromosomal Mutations", tab: "Q3", group: 31 },
        { code: "32A", name: "Fossil Evidence", tab: "Q4", group: 32 },
        { code: "32B", name: "Anatomical Evidence", tab: "Q4", group: 32 },
        { code: "33A", name: "DNA Sequence Evidence", tab: "Q4", group: 33 },
        { code: "33B", name: "Protein & Amino Acid Evidence", tab: "Q4", group: 33 },
        { code: "34A", name: "Darwin's Four Principles", tab: "Q4", group: 34 },
        { code: "34B", name: "Adaptation & Descent with Modification", tab: "Q4", group: 34 },
        { code: "35A1", name: "Genetic Drift", tab: "Q4", group: 35 },
        { code: "35A2", name: "Bottleneck & Founder Effects", tab: "Q4", group: 35 },
        { code: "35A3", name: "Gene Flow", tab: "Q4", group: 35 },
        { code: "35B", name: "Patterns of Selection", tab: "Q4", group: 35 },
        { code: "36", name: "Speciation", tab: "Q4", group: 36 },
        { code: "37A", name: "Digestive System", tab: "Q4", group: 37 },
        { code: "37B", name: "Excretory System", tab: "Q4", group: 37 },
        { code: "37C1", name: "Heart Anatomy & Blood Flow", tab: "Q4", group: 37 },
        { code: "37C2", name: "Blood Vessels", tab: "Q4", group: 37 },
        { code: "38A", name: "Defining Homeostasis", tab: "Q4", group: 38 },
        { code: "38B1", name: "Negative Feedback Loops", tab: "Q4", group: 38 },
        { code: "38B2", name: "Positive Feedback Loops", tab: "Q4", group: 38 }
    ]
};
