window.COURSE_CONFIG = {
    slug: "environmental-biology",
    title: "Environmental Biology Study Resources",
    subtitle: "Click a topic to see videos and readings. Scan QR codes with your phone!",
    icon: "🌍",
    sheetUrl: "https://docs.google.com/spreadsheets/d/e/2PACX-1vReEbbwpIWoOi1L6pOOR_u_HowMLyZusBbe3F6g32fmi6EY7wXa-72eDs11HTB_H5t_BBFt14VF5I3b/pub?output=csv",
    tabs: [
        { id: "all", label: "All Topics" },
        { id: "U1", label: "U1: Systems Thinking" },
        { id: "U2", label: "U2: Earth's Spheres" },
        { id: "U3", label: "U3: Matter & Energy" },
        { id: "U4", label: "U4: Sphere Interactions" },
        { id: "U5", label: "U5: Ecology & Populations" },
        { id: "U6", label: "U6: Environmental Challenges" },
        { id: "U7", label: "U7: Case Studies" },
        { id: "U8", label: "U8: Solutions & Sustainability" }
    ],
    topics: [
        // Unit 1: Systems Thinking Foundation
        { code: "1.1", name: "What is a System?", tab: "U1", group: 1 },
        { code: "1.2", name: "Stocks and Flows", tab: "U1", group: 1 },
        { code: "1.3", name: "System Boundaries", tab: "U1", group: 1 },
        { code: "1.4", name: "Reinforcing Feedback Loops", tab: "U1", group: 2 },
        { code: "1.5", name: "Balancing Feedback Loops", tab: "U1", group: 2 },
        { code: "1.6", name: "Delays and Time Lags", tab: "U1", group: 3 },
        { code: "1.7", name: "Thresholds & Tipping Points", tab: "U1", group: 3 },
        { code: "1.8", name: "Leverage Points", tab: "U1", group: 4 },
        { code: "1.9", name: "Reading Environmental Data", tab: "U1", group: 5 },
        { code: "1.10", name: "Your Body as a System", tab: "U1", group: 6 },
        // Unit 2: Earth's Spheres
        { code: "2.1A", name: "What is Environmental Biology?", tab: "U2", group: 7 },
        { code: "2.1B", name: "The Biosphere", tab: "U2", group: 7 },
        { code: "2.2", name: "The Geosphere — Structure", tab: "U2", group: 8 },
        { code: "2.3", name: "The Geosphere — Tectonic Forces", tab: "U2", group: 8 },
        { code: "2.4", name: "The Geosphere — Rock & Surface Processes", tab: "U2", group: 8 },
        { code: "2.5", name: "The Hydrosphere — Water on Earth", tab: "U2", group: 9 },
        { code: "2.6", name: "The Hydrosphere — Ocean Systems", tab: "U2", group: 9 },
        { code: "2.7", name: "The Cryosphere", tab: "U2", group: 10 },
        { code: "2.8", name: "The Atmosphere — Structure", tab: "U2", group: 11 },
        { code: "2.9", name: "The Atmosphere — Energy & Weather", tab: "U2", group: 11 },
        { code: "2.11", name: "The Pedosphere — Soil", tab: "U2", group: 12 },
        { code: "2.12", name: "The Anthroposphere", tab: "U2", group: 13 },
        { code: "2.12E", name: "The Anthropocene", tab: "U2", group: 13 },
        { code: "2.13", name: "Earth as a System", tab: "U2", group: 14 },
        // Unit 3: Matter & Energy
        { code: "3.1A", name: "Energy Flow — Sun to Earth", tab: "U3", group: 15 },
        { code: "3.1B", name: "The Carbon Cycle — Overview", tab: "U3", group: 15 },
        { code: "3.2", name: "Ecosystem Energy Flow", tab: "U3", group: 16 },
        { code: "3.3", name: "Photosynthesis", tab: "U3", group: 16 },
        { code: "3.4", name: "Carbon & Nitrogen Cycles", tab: "U3", group: 17 },
        { code: "3.5", name: "Food Chains & Food Webs", tab: "U3", group: 16 },
        { code: "3.6", name: "Food Web Construction & Energy Pyramids", tab: "U3", group: 16 },
        { code: "3.7", name: "The Water Cycle", tab: "U3", group: 18 },
        { code: "3.8", name: "Decomposition & Nutrient Cycling", tab: "U3", group: 17 },
        { code: "3.9", name: "Carbon Capture & Greenhouse Gases", tab: "U3", group: 15 },
        { code: "3.11", name: "Fast vs. Slow Carbon Cycle", tab: "U3", group: 15 },
        { code: "3.12", name: "Nitrogen Cycle — Importance", tab: "U3", group: 19 },
        { code: "3.13", name: "Nitrogen Cycle — Processes", tab: "U3", group: 19 },
        { code: "3.14", name: "The Phosphorus Cycle", tab: "U3", group: 19 },
        { code: "3.15", name: "The Sulfur Cycle & Acid Rain", tab: "U3", group: 20 },
        { code: "3.16", name: "Comparing Biogeochemical Cycles", tab: "U3", group: 20 },
        { code: "3.17", name: "Your Body in the Cycles", tab: "U3", group: 21 },
        // Unit 4: Sphere Interactions
        { code: "4.1", name: "Atmosphere Interactions", tab: "U4", group: 22 },
        { code: "4.2", name: "Hydrosphere Interactions", tab: "U4", group: 22 },
        { code: "4.3", name: "Geosphere-Biosphere Interactions", tab: "U4", group: 22 },
        { code: "4.4", name: "Cryosphere Interactions", tab: "U4", group: 22 },
        { code: "4.5", name: "Pedosphere Interactions", tab: "U4", group: 22 },
        // Unit 5: Ecology & Populations
        { code: "5.1A", name: "Population Definition & Measurement", tab: "U5", group: 23 },
        { code: "5.1B", name: "Population Growth Models", tab: "U5", group: 23 },
        { code: "5.2", name: "Population Biology & Dynamics", tab: "U5", group: 23 },
        { code: "5.3", name: "Carrying Capacity & Limiting Factors", tab: "U5", group: 24 },
        { code: "5.4", name: "Habitat Change & Population Effects", tab: "U5", group: 24 },
        { code: "5.5", name: "Community Ecology — Competition", tab: "U5", group: 25 },
        { code: "5.6", name: "Predation & Herbivory", tab: "U5", group: 25 },
        { code: "5.7", name: "Symbiosis & Coevolution", tab: "U5", group: 25 },
        { code: "5.8", name: "Keystone Species & Trophic Cascades", tab: "U5", group: 26 },
        { code: "5.9", name: "Ecological Succession", tab: "U5", group: 27 },
        { code: "5.11", name: "Terrestrial Biomes", tab: "U5", group: 28 },
        { code: "5.12", name: "Aquatic Biomes & Freshwater", tab: "U5", group: 28 },
        { code: "5.13", name: "Freshwater Systems & Eutrophication", tab: "U5", group: 29 },
        { code: "5.14", name: "Marine Systems", tab: "U5", group: 29 },
        { code: "5.15", name: "You in the Food Web", tab: "U5", group: 30 },
        // Unit 6: Environmental Challenges
        { code: "6.1A", name: "Climate Change Overview", tab: "U6", group: 31 },
        { code: "6.1B", name: "Biodiversity Loss", tab: "U6", group: 32 },
        { code: "6.2", name: "Climate Change — Evidence & Science", tab: "U6", group: 31 },
        { code: "6.3", name: "Climate Feedbacks & Tipping Points", tab: "U6", group: 31 },
        { code: "6.4", name: "Climate Impacts & Extreme Weather", tab: "U6", group: 31 },
        { code: "6.5", name: "Air Pollution", tab: "U6", group: 33 },
        { code: "6.6", name: "Water Pollution", tab: "U6", group: 33 },
        { code: "6.7", name: "Soil Degradation", tab: "U6", group: 33 },
        { code: "6.8", name: "Toxicology & Health Impacts", tab: "U6", group: 34 },
        { code: "6.9", name: "Biodiversity & Conservation", tab: "U6", group: 32 },
        { code: "6.11", name: "Human Environmental Impacts", tab: "U6", group: 35 },
        { code: "6.12", name: "Toward a Sustainable Future", tab: "U6", group: 36 },
        { code: "6.13", name: "Environmental Justice", tab: "U6", group: 37 },
        { code: "6.14", name: "Pollution in Your Body", tab: "U6", group: 34 },
        // Unit 7: Case Studies
        { code: "7.1A", name: "The Dust Bowl", tab: "U7", group: 38 },
        { code: "7.1B", name: "Cross-Case Patterns & Synthesis", tab: "U7", group: 38 },
        { code: "7.2", name: "The Aral Sea", tab: "U7", group: 39 },
        { code: "7.3", name: "Gulf of Mexico Dead Zone", tab: "U7", group: 39 },
        { code: "7.4", name: "Coral Reef Decline", tab: "U7", group: 39 },
        { code: "7.5", name: "The Ozone Hole", tab: "U7", group: 40 },
        { code: "7.6", name: "Acid Rain", tab: "U7", group: 40 },
        { code: "7.7", name: "Biomes & Atmospheric Circulation", tab: "U7", group: 40 },
        { code: "7.8", name: "Wolves of Yellowstone", tab: "U7", group: 38 },
        { code: "7.9", name: "The Charles River", tab: "U7", group: 38 },
        { code: "7.10", name: "Massachusetts Environmental Stories", tab: "U7", group: 38 },
        // Unit 8: Solutions & Sustainability
        { code: "8.1", name: "Leverage Points & Systems Solutions", tab: "U8", group: 1 },
        { code: "8.2", name: "Energy Efficiency", tab: "U8", group: 2 },
        { code: "8.3", name: "Renewable Energy", tab: "U8", group: 2 },
        { code: "8.4", name: "Transportation & Fuel Alternatives", tab: "U8", group: 2 },
        { code: "8.5", name: "Conservation & Restoration", tab: "U8", group: 3 },
        { code: "8.6", name: "Sustainable Agriculture & Land Use", tab: "U8", group: 4 },
        { code: "8.7", name: "Carbon Capture & Technology", tab: "U8", group: 5 },
        { code: "8.8", name: "Individual & Collective Action", tab: "U8", group: 6 },
        { code: "8.9", name: "Policy & International Agreements", tab: "U8", group: 6 },
        { code: "8.10", name: "Citizen Science", tab: "U8", group: 7 }
    ]
};
